name: Build and Publish GpioSimulator

on:
  push:
    branches: [ master ]
    
    paths-ignore:
      - '**/*.md'
      - 'docs/**'

jobs:
  publish:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Avoid shallow clone so NBGV can do its work.
          submodules: 'recursive'
          
      - name: Set version
        uses: dotnet/nbgv@v0.4.2
        with:
          setAllVars: true
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x
            
      - name: Install dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release --no-restore -p:ContinuousIntegrationBuild=true -p:DeterministicSourcePaths=true
        
      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal -p:ContinuousIntegrationBuild=true -p:DeterministicSourcePaths=true
        
      - name: Publish Common
        uses: alirezanet/publish-nuget@v3.1.0
        with:
          PROJECT_FILE_PATH: src/DevDecoder.GpioSimulator.Common/DevDecoder.GpioSimulator.Common.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY_UNCLETHARGY}}
          INCLUDE_SYMBOLS: true
          VERSION_STATIC: ${{env.NBGV_Version}}

      - name: Publish Core Shim
        uses: alirezanet/publish-nuget@v3.1.0
        with:
          PROJECT_FILE_PATH: src/System.Device.Gpio/System.Device.Gpio.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY_UNCLETHARGY}}
          INCLUDE_SYMBOLS: true
          VERSION_STATIC: ${{env.NBGV_Version}}

      - name: Publish Local Driver
        uses: alirezanet/publish-nuget@v3.1.0
        with:
          PROJECT_FILE_PATH: src/DevDecoder.GpioSimulator.Drivers/DevDecoder.GpioSimulator.Drivers.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY_UNCLETHARGY}}
          INCLUDE_SYMBOLS: true
          VERSION_STATIC: ${{env.NBGV_Version}}
